{
 "title": "Host",
 "description": "Host Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "label_values(host)" }
  ]
 },
 "panels": [
  { "title": "${host}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Current Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(host_memory_total_bytes{host=\"${host}\"} - host_memory_avail_bytes{host=\"${host}\"}) / host_memory_total_bytes{host=\"${host}\"} * 100"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_jobs_running{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Current 1m Load",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_load_1m{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_total_bytes{host=\"${host}\"} - host_memory_avail_bytes{host=\"${host}\"}",
     "legendFormat": "used"
    },
    {
     "expr": "host_memory_total_bytes{host=\"${host}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_jobs_running{host=\"${host}\"}",
     "legendFormat": "running"
    },
    {
     "expr": "host_jobs_starting{host=\"${host}\"}",
     "legendFormat": "starting"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_1m{host=\"${host}\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "host_load_5m{host=\"${host}\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "host_load_15m{host=\"${host}\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  { "title": "${host}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(host_memory_total_bytes{host=\"${host}\"} - host_memory_avail_bytes{host=\"${host}\"}) / host_memory_total_bytes{host=\"${host}\"} * 100"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_jobs_running{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Current 1m Load",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_load_1m{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_total_bytes{host=\"${host}\"} - host_memory_avail_bytes{host=\"${host}\"}",
     "legendFormat": "used"
    },
    {
     "expr": "host_memory_total_bytes{host=\"${host}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_jobs_running{host=\"${host}\"}",
     "legendFormat": "running"
    },
    {
     "expr": "host_jobs_starting{host=\"${host}\"}",
     "legendFormat": "starting"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_1m{host=\"${host}\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "host_load_5m{host=\"${host}\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "host_load_15m{host=\"${host}\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  { "title": "${host}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Current Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(host_memory_total_bytes{host=\"${host}\"} - host_memory_avail_bytes{host=\"${host}\"}) / host_memory_total_bytes{host=\"${host}\"} * 100"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_jobs_running{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Current 1m Load",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_load_1m{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_total_bytes{host=\"${host}\"} - host_memory_avail_bytes{host=\"${host}\"}",
     "legendFormat": "used"
    },
    {
     "expr": "host_memory_total_bytes{host=\"${host}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_jobs_running{host=\"${host}\"}",
     "legendFormat": "running"
    },
    {
     "expr": "host_jobs_starting{host=\"${host}\"}",
     "legendFormat": "starting"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_1m{host=\"${host}\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "host_load_5m{host=\"${host}\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "host_load_15m{host=\"${host}\"}",
     "legendFormat": "load 15m"
    }
   ]
  }
 ]
}