#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "${ROOT}/script/lib/ui.sh"

usage() {
  cat <<USAGE >&2
usage: $0 [options]

Build Flynn using the builder image.

OPTIONS:
  -h, --help              Show this message
  -v, --verbose           Be verbose
  -x, --version=VERSION   Explicit version to use [default: dev]
  -t, --tuf-keys=KEYS     TUF root keys
  --git-version           Generate the version using git status
USAGE
}

main() {
  local version="dev"
  local verbose=false
  local tuf_keys=""

  while true; do
    case "$1" in
      -h | --help)
        usage
        exit 0
        ;;
      -v | --verbose)
        verbose=true
        shift
        ;;
      -x | --version)
        if [[ -z "$2" ]]; then
          fail "--version flag requires an argument"
        fi
        version="$2"
        shift 2
        ;;
      -t | --tuf-keys)
        if [[ -z "$2" ]]; then
          fail "--tuf-keys flag requires an argument"
        fi
        tuf_keys="$2"
        shift 2
        ;;
      --git-version)
        version="$(git_version)"
        shift
        ;;
      *)
        break
        ;;
    esac
  done

  if [[ $# -ne 0 ]]; then
    usage
    exit 1
  fi

  local flynn_host="${ROOT}/build/bin/flynn-host"

  # if building from clean, download binaries + images
  if ! [[ -e "${flynn_host}" ]]; then
    local sha="132903ae94d7c1b174261e738424b94022233d938ef091659727a30bddeb7a61d114b762f0fc2ffeecb967aef87d92bc71a79b9c3df31220c24ee9d8d83fa932"
    local url="https://s3.amazonaws.com/flynn-temp/tuf/targets/${sha}.flynn-host.gz"

    info "downloading flynn-host from ${url}"
    mkdir -p "${ROOT}/build/bin"
    curl -fsSLo "${flynn_host}.gz" "${url}"
    echo "${sha}  ${flynn_host}.gz" | shasum -a "512" -c -
    gunzip --force "${flynn_host}.gz"
    chmod +x "${flynn_host}"

    info "downloading binaries + images"
    local version="dev"
    mkdir -p "${ROOT}/build/manifests"
    sudo FLYNN_VERSION="${version}" "${flynn_host}" download \
      --repository "https://s3.amazonaws.com/flynn-temp/tuf" \
      --tuf-db     "${ROOT}/build/tuf.db" \
      --bin-dir    "${ROOT}/build/bin" \
      --config-dir "${ROOT}/build/manifests" \
      --volpath    "/var/lib/flynn/volumes-0"

    mkdir -p "${ROOT}/build/image"
    jq '.builder' "${ROOT}/build/manifests/images.${version}.json" > "${ROOT}/build/image/builder.json"
  fi

  # bootstrap the cluster if not running
  if ! curl -fsSLo /dev/null --connect-timeout 1 "http://1.localflynn.com:1111/.well-known/status"; then
    info "Flynn cluster not running, bootstrapping"
    "${ROOT}/script/bootstrap-flynn"
  fi

  local args=("--version" "${version}")
  if $verbose; then
    args+=("--verbose")
  fi
  if [[ -n "${tuf_keys}" ]]; then
    args+=("--tuf-keys" "${tuf_keys}")
  fi

  sudo mkdir -p "/var/lib/flynn/layer-cache"
  export DISCOVERD="http://1.localflynn.com:1111"
  "${flynn_host}" run \
    --bind    "${ROOT}:${ROOT},/var/lib/flynn/layer-cache:/var/lib/flynn/layer-cache" \
    --limits  "temp_disk=1G" \
    --workdir "${ROOT}" \
    "${ROOT}/build/image/builder.json" \
    /usr/bin/env \
    GOPATH="${GOPATH}" \
    /bin/flynn-builder build ${args[@]}

  local dir="${ROOT}/build"

  # extract binaries into build/bin
  extract_bin "host"              "/usr/local/bin/flynn-host"
  extract_bin "host"              "/usr/local/bin/flynn-init"
  extract_bin "cli-linux-amd64"   "/bin/flynn-linux-amd64"
  extract_bin "cli-linux-amd64"   "/bin/flynn-linux-amd64"
  extract_bin "cli-linux-386"     "/bin/flynn-linux-386"
  extract_bin "cli-darwin-amd64"  "/bin/flynn-darwin-amd64"
  extract_bin "cli-freebsd-amd64" "/bin/flynn-freebsd-amd64"
  extract_bin "cli-windows-amd64" "/bin/flynn-windows-amd64"
  extract_bin "cli-windows-386"   "/bin/flynn-windows-386"
  extract_bin "release"           "/bin/flynn-release"
  extract_bin "builder"           "/bin/flynn-builder"
  extract_bin "discoverd"         "/bin/discoverd"
  extract_bin "test"              "/bin/flynn-test-file-server"
  ln -nfs "flynn-linux-amd64" "${ROOT}/build/bin/flynn"

  # extract GOROOT from the Go image into build/go so we
  # can run unit tests on the host
  extract_dir "go" "/usr/local/go"
}

git_version() {
  local commit="$(git rev-parse --short HEAD)"
  if [[ -z "${commit}" ]]; then
    fail "unable to determine Git commit"
  fi

  # if there are tags like 'vYYYYMMDD.N' pointing at HEAD, use the most recent
  # one suffixed with the commit
  local tag="$(git tag --list "v*" --sort "v:refname" --points-at HEAD 2>/dev/null | tail -n 1)"
  if [[ -n "${tag}" ]]; then
    echo "${tag}-${commit}"
    return
  fi

  # use the branch and commit, appending a '+' if the index is dirty
  local branch="$(git rev-parse --abbrev-ref HEAD)"
  local version="${branch}-${commit}"
  if [[ -n "$(git status --porcelain)" ]]; then
    version="${version}+"
  fi
  echo "${version}"
}

extract_bin() {
  local name=$1
  local bin=$2

  local image="${ROOT}/build/image/${name}.json"
  local id="$(jq --raw-output '.meta["manifest.id"]' "${image}")"
  if [[ -z "${id}" ]]; then
    fail "unable to determine ${name} image ID"
  fi

  local dst="${ROOT}/build/bin/$(basename ${bin})"
  if ! [[ -e "${dst}.${id}" ]]; then
    info "extracting $(basename ${bin}) binary from image ${id}"
    "${flynn_host}" run "${image}" cat "${bin}" > "${dst}.${id}"
    chmod +x "${dst}.${id}"
  fi

  ln -nfs "$(basename ${dst}.${id})" "${dst}"
}

extract_dir() {
  local name=$1
  local dir=$2

  local image="${ROOT}/build/image/${name}.json"
  local id="$(jq --raw-output '.meta["manifest.id"]' "${image}")"
  if [[ -z "${id}" ]]; then
    fail "unable to determine ${name} image ID"
  fi

  local dst="${ROOT}/build/$(basename ${dir})"
  if ! [[ -d "${dst}.${id}" ]]; then
    info "extracting $(basename ${dir}) directory from image ${id}"
    mkdir -p "${dst}.${id}"
    "${flynn_host}" run "${image}" tar cf - -C "${dir}" . | tar xf - -C "${dst}.${id}"
    sudo chown -R "$(id --user):$(id --group)" "${dst}.${id}"
  fi

  ln -nfs "${dst}.${id}" "${dst}"
}

main $@
